import type { NextPage } from 'next'
import Head from 'next/head'
import styles from "../styles/pages/Home.module.scss";
import { createMachine, Machine } from "xstate";
import { useMachine } from "@xstate/react";
import Link from "next/link";

const Home: NextPage = () => {
  const [machine, send] = useMachine(
    createMachine({
      initial: "toggledOff",
      states: {
        toggledOn: {
          on: {
            TOGGLE: "toggledOff",
          },
        },
        toggledOff: {
          on: {
            TOGGLE: "toggledOn",
          },
        },
      },
    })
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Home Page</h1>
        <input
          className={styles.button}
          type="button"
          value={machine.value.toString()}
          onClick={() => send("TOGGLE")}
        />
        <Link href="/blog" passHref>
          <input
            className={styles.button}
            type="button"
            value={"Go to Blog Page"}
          />
        </Link>
      </main>

      <footer className={styles.footer}>Footer Section</footer>
    </div>
  );
};

export default Home
