import type { NextPage } from 'next'
import Head from 'next/head'
import PageStyles from "../styles/pages/Home.module.scss";
import { createMachine, Machine } from "xstate";
import { useMachine } from "@xstate/react";
import Link from "next/link";

const Home: NextPage = () => {
  const [machine, send] = useMachine(
    createMachine({
      initial: "toggledOff",
      states: {
        toggledOn: {
          on: {
            TOGGLE: "toggledOff",
          },
        },
        toggledOff: {
          on: {
            TOGGLE: "toggledOn",
          },
        },
      },
    })
  );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={PageStyles.main}>
        <section className={PageStyles.LandingSection}>
          <h1>Landing Section</h1>
          <input
            className={PageStyles.button}
            type="button"
            value={machine.value.toString()}
            onClick={() => send("TOGGLE")}
          />
        </section>
        <section className={PageStyles.UserProgressSection}>
          Continue where you left off
          <Link href="/blog" passHref>
            <input
              className={PageStyles.button}
              type="button"
              value={"Go to Blog Page"}
            />
          </Link>
          <Link href="/course" passHref>
            <input
              className={PageStyles.button}
              type="button"
              value={"Go to Course Page"}
            />
          </Link>
        </section>
        <section className={PageStyles.UserStatsSection}>
          Stats and progress stuff
        </section>
      </main>
    </>
  );
};

export default Home
